const PREPARE_SIMULATION_REQUEST = 1;
const PREPARE_SIMULATION_RESPONSE = 2;
const START_SIMULATION_REQUEST = 3;
const START_SIMULATION_RESPONSE = 4;
const CREATE_CAR_INFO = 5;
const UPDATE_CAR_INFO = 6;
const KILL_CAR_INFO = 7;
const SWITCH_LIGHTS_INFO = 8;
const CREATE_TROUBLE_POINT_INFO = 10;

export {
  PREPARE_SIMULATION_REQUEST,
  PREPARE_SIMULATION_RESPONSE,
  START_SIMULATION_REQUEST,
  START_SIMULATION_RESPONSE,
  CREATE_CAR_INFO,
  UPDATE_CAR_INFO,
  KILL_CAR_INFO,
  SWITCH_LIGHTS_INFO,
  CREATE_TROUBLE_POINT_INFO,
};
