const PREPARE_SIMULATION_REQUEST = 1;
const PREPARE_SIMULATION_RESPONSE = 2;
const START_SIMULATION_REQUEST = 3;
const START_SIMULATION_RESPONSE = 4;
const CREATE_CAR_INFO = 5;

export {
  PREPARE_SIMULATION_REQUEST,
  PREPARE_SIMULATION_RESPONSE,
  START_SIMULATION_REQUEST,
  START_SIMULATION_RESPONSE,
  CREATE_CAR_INFO,
};
